server:
  port: 8082

spring:
  application:
    name: eureka-client1

eureka:
  client:
    # 注册本服务到注册中心
    register-with-eureka: true
    # 获取服务实例
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka/
