server:
  port: 8088
spring:
  application:
    name: ribbon-service1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
service-url:
  user-service: http://user-service